Table producto{
  id int [primary key]
  nombre text [primary key]
  precio float [not null]
  stock int [default: 0]
}
Table cliente{
  id int [primary key]
  rut text [unique, not null]
  nombre text [primary key]
  carrera text [not null]
}
Table cliente_compra_producto{
  id_compra int  [primary key]
  id_producto int [ref: > producto.id]
  id_cliente int [ref: > cliente.id]
}